config/routes.rb
Rails.application.routes.draw do
  root "cars#index"
  devise_for :users
  post 'checkout/sell/:id', to: "checkout#sell", as: :checkout_sell
  post 'checkout/rent/:id', to: "checkout#rent", as: :checkout_rent
  patch 'set_dealer', to: "cars#set_dealer", as: :set_dealer
  get 'search_for_cars', to: 'cars#search_for_cars'
  resources :cars do
    delete 'delete_car_image', on: :member
  end

  # for transction 
  resources :car_transactions do
    get 'car_sell_payment', on: :member
    post 'sell_payment', on: :collection
    post 'paypal_payment_response', on: :collection
  end
end

app/controllers/car_transactions_controller.rb
class CarTransactionsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :authenticate_user!, only: %i[car_sell_payment]
  before_action :set_car

  # GET /car_transactions/:id/car_sell_payment
  def car_sell_payment
    session[:car_id] = @car.id
  end

  # POST /car_transactions/sell_payment ( for Buy )
  def sell_payment
    psp = Psp.find_or_create_by!(type: @car.payment_gateway?)
    transaction = CarTransaction.create!(car_id: @car.id, owner_id: @car.owner.id, psp_id:psp.id, buyer_id: current_user.id , status: "processing")
    response = transaction.psp.sell_car(transaction.id) 
    
    binding.pry
    
    respond_to do |format|
      if transaction.psp.type == "PaypalPsp"
        format.json { render :json => {:token => response.result.id}, :status => :ok }
      elsif transaction.psp.type == "StripePsp"
        @session = response
        format.js
      else
      end
    end
  end  

  # POST	/car_transactions/paypal_payment_response  ( Getting Response from Payment Gateways )
  def paypal_payment_response
    @car_transaction = CarTransaction.find(session[:transaction_id])
    response = @car_transaction.psp.payment_response(@car_transaction.id,params[:transaction_token])
    session[:transaction_id]= nil
    session[:car_id]= nil
    return render :json => {:status => response.result.status}, :status => :ok
  end

  private
  def set_car
    @car =  params[:id] ? Car.friendly.find(params[:id]) : Car.friendly.find(session[:car_id]) 
  end
end

app/views/car_transactions/car_sell_payment.html.erb
<% if @car.payment_gateway? == "PaypalPsp" %>
  <div id="paypal-button-container"></div>
  <script src="https://www.paypal.com/sdk/js?client-id=<%=@car.owner.Public_key%>"></script>
  <script>
    paypal.Buttons({
    env: 'sandbox', // Valid values are sandbox and live.
    createOrder: async () => {
    const response = await fetch(`/car_transactions/sell_payment`, {method: 'POST'});
    const responseData = await response.json(); 
    console.log("--------createOrder-----------")
    return responseData.token;
    },
    onApprove: async (data) => {
    const response = await fetch('/car_transactions/paypal_payment_response', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({transaction_token: data.orderID, data: data})
    });
    const responseData = await response.json();
    if (responseData.status === 'COMPLETED') {
      alert('COMPLETED');
      console.log(responseData)
      // REDIRECT TO SUCCESS PAGE
    }
    }
    }).render('#paypal-button-container');
  </script>
<% elsif @car.payment_gateway? == "StripePsp" %>
  <%= button_to "Pay Now",sell_payment_car_transactions_path, class:"btn btn-outline-success btn-sm", data:{ turbo: false}, remote: true %>
<% end %>

app/views/car_transactions/sell_payment.js.erb
var stripe = Stripe("<%=@car.owner.Public_key%>");
<% puts "-------------------------------------------------------"%>
<% puts @session.id %>
stripe.redirectToCheckout({
sessionId: "<%= @session.id %>"
}).then(function (result) {
});     