config/routes.rb
Rails.application.routes.draw do
  root "cars#index"
  devise_for :users
  post 'checkout/sell/:id', to: "checkout#sell", as: :checkout_sell
  post 'checkout/rent/:id', to: "checkout#rent", as: :checkout_rent
  patch 'set_dealer', to: "cars#set_dealer", as: :set_dealer
  get 'search_for_cars', to: 'cars#search_for_cars'
  resources :cars do
    delete 'delete_car_image', on: :member
  end

  # for transction 
  resources :car_transactions do
    get 'car_sell_payment', on: :member
    post 'sell_payment', on: :collection
    post 'paypal_payment_response', on: :collection
  end
end

app/models/car.rb
class Car < ApplicationRecord
  attr_accessor :sell_checked
  attr_accessor :rent_checked
  attr_accessor :invalid_purpose
  searchkick text_middle: [:company, :model]
  extend FriendlyId
  friendly_id :slug_candidates, use: :slugged
  has_many :rents
  has_many :users, through: :rents, dependent: :destroy
  belongs_to :owner, class_name: "User"
  has_one_attached :main_car_image, dependent: :destroy
  has_many_attached :car_images
  has_many :car_transactions
  validates :company, :model, :purchase_date, 
            :car_description, :registered_number, presence: true
  validates :registered_number, presence: true, uniqueness: true 
  validates :seats, :distance_driven, numericality: { only_integer: true }, presence: true       
  enum engine_type: [:Petrol, :Diesel, :Hybrid, :EV ]
  enum car_type: [:Hatchback, :Sedan, :SUV, :Supercar]
  enum transmission_type: [:Manual, :Automatic]
  enum car_status: [:active, :rent, :sold] 

  # serialize :purpose, Array
  validates :sell_price, presence: true, if: :sell_checked
  validates :rent_price, presence: true, if: :rent_checked
  validates :purpose, presence: { message: "Car should be available for one purpose" }, if: :invalid_purpose
  
  # callback
  # after_update :generate_reindex_for_searchkick
  
  # to generate reindex for searchkick
  # def generate_reindex_for_searchkick
  #   reindex
  # end

  # to check car images
  def has_car_images?
    car_images_attachments != []
  end

  # to add slug_candidates
  def slug_candidates
    [
      [:company, :registered_number, :car_type]
    ]
  end

  def currently_rent_by
    if car_status == "rent"
      current_renter = rents.last.user
    else
      "Car is Available for Rent"
    end
  end

  def rent_by_all
    all_renters = []
    rents.each do |renter|  # rents is association method cause we have one to many between car - rents
      all_renters.push(renter.user)
    end
    return all_renters
  end

  def payment_gateway?
    owner.payment_gateway
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:create_paypal_car, :capture_paypal_car] 
  before_action :set_car, only: %i[ show edit update destroy delete_car_image]
  authorize_resource
  skip_authorize_resource only: [:set_dealer, :delete_car_image, :paypal_car_payment, :create_paypal_car, :capture_paypal_car]

  # GET /cars or /cars.json
  def index
    search = params[:query].present? ? params[:query] : nil
    if search
      @cars =  Car.search(search, fields: [{company: :text_middle}, {model: :text_middle}])
      @cars= Car.where(owner_id: current_user.id) if params[:my_cars] && current_user
    else
      @cars = Car.all
      @cars = Car.where.not(owner_id: current_user.id) if current_user
      @cars= Car.where(owner_id: current_user.id) if params[:my_cars] && current_user
    end
  end

  # GET /cars/1 or /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    if current_user.Secret_key==nil
      @user = current_user
      render :become_dealer
    else
      @car = Car.new
    end
  end

  def set_dealer
    @user = current_user
    @user.check_for_dealer = true
    if @user.update(dealer_params)
      redirect_to new_car_path
    else
      render :become_dealer, status: :unprocessable_entity
    end 
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars or /cars.json
  def create
    @car = Car.new(car_params)
    validate_car(@car)
    respond_to do |format|
      if @car.save
        add_to_car(@car)
        @car.save
        format.html { redirect_to car_url(@car), notice: "Car was successfully created." }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1 or /cars/1.json
  def update
    validate_car(@car)
      respond_to do |format|
        if @car.update(car_params)
          add_to_car(@car)
          @car.save
          format.html { redirect_to car_url(@car), notice: "Car was successfully updated." }
          format.json { render :show, status: :ok, location: @car }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @car.errors, status: :unprocessable_entity }
        end
    end
  end

  # DELETE /cars/1 or /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: "Car was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  # DELETE /cars/1/car_image
  def delete_car_image
    @car_image = @car.car_images.find(params[:image_id])
    @car_image.purge
    respond_to do |format|
      format.html { redirect_to edit_car_url(@car), notice: 'car image was successfully destroyed.' }
    end
  end

  # autocomplete /cars/search_for_cars?query
  def search_for_cars
    render json: Car.search(params[:query], fields: ["model", "company"],match: :text_middle,limit: 10,load: false, misspellings: {below: 5}).map(&:company)
  end
  
  # paypal payment 
  def paypal_car_payment
    session[:car_id] = params[:id]
    PaypalService.new(session[:car_id]).create_car
  end
  
  # /create_paypal_car
  def create_paypal_car
    response = PaypalService.new(session[:car_id]).create_car
    return render :json => {:token => response.result.id}, :status => :ok
  end

  # /capyure_paypal_car
  def capture_paypal_car
    response = PaypalService.new(session[:car_id]).capture_car(params[:order_id])
    return render :json => {:status => response.result.status}, :status => :ok
  end

  private
  
  def set_car
    @car = Car.friendly.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def car_params
    params.require(:car).permit(:company,:main_car_image, :model, :purchase_date, :engine_type, :car_type, :seats,:owner_id, :distance_driven, :transmission_type, :car_description, :registered_number, car_images: [])
  end

  def dealer_params
    params.require(:user).permit(:payment_gateway, :Secret_key, :Public_key)
  end

  # ------ To check optional validation -------
  def validate_car(car)
    if params[:car][:sell] == "1" && ( params[:car][:sell_price] == "" || params[:car][:sell_price] == "0" || params[:car][:sell_price] < "0" )
      car.sell_checked = true
      car.sell_price = nil
    end

    if params[:car][:rent] == "1" && ( params[:car][:rent_price] == "" || params[:car][:rent_price] == "0" || params[:car][:rent_price] < "0" )
      car.rent_checked = true
      car.rent_price = nil
    end

    if params[:car][:sell] == "0" && params[:car][:rent] == "0"
      car.invalid_purpose = true
      car.purpose.clear
    end
  end

  # ------- To add optional value to object -------
  def add_to_car(car)
    if params[:car][:sell] == "1"
      if !car.purpose.include?("sell")
        car.purpose.push("sell")
      end
      car.sell_price = params[:car][:sell_price]
    else
      car.purpose.delete("sell")
      car.sell_price = nil 
    end

    if params[:car][:rent] == "1"
      if !car.purpose.include?("rent")
        car.purpose.push("rent")
      end
      car.rent_price = params[:car][:rent_price]
    else
      car.purpose.delete("rent")
      car.rent_price = nil
    end
  end
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_car.html.erb
<div class="shadow car_image_card mx-3 my-3" style="width: 18rem;height: 25rem;">
  <div>
    <div style="height:198px;width:262px;">
      <%= link_to car_path(car) do %>
      <% if car.main_car_image.key?%>
          <p>
            <%= cl_image_tag(car.main_car_image.key) %>
          </p>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="card-body mt-5">
    <p>Car Name: <%= car.company %> <%= car.model %> </p>
    <p>Kms Covered: <%= car.distance_driven %></p>
    <div class="wrapper d-flex flex-column justify-content-between">
      <% if car.owner != current_user %>
        <% if car.sell_price %>
          <div class="d-flex align-items-center justify-content-between">
            <strong>Sell-Price: <%= car.sell_price %></strong>
             <%= link_to "Buy",car_sell_payment_car_transaction_path(car), class:"btn btn-outline-primary btn-sm", data: { turbo: false } %>
          </div>
        <% end %>
        <% if car.rent_price %>
          <div class="d-flex align-items-center justify-content-between mt-3">
            <p><strong>Rent-Price: <%= car.rent_price %></strong></p>
             <%= button_to "Rent",checkout_rent_path(car), class:"btn btn-outline-success btn-sm", data: { turbo: false }, remote: true %>
          </div>
        <% end %>
      <% else %>
        <% if car.sell_price %>
          <div class="d-flex align-items-center justify-content-between">
            <strong>Sell-Price: <%= car.sell_price %></strong>
          </div>
        <% end %>
        <% if car.rent_price %>
          <div class="d-flex align-items-center justify-content-between mt-1">
            <strong>Rent-Price: <%= car.rent_price %></strong>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/cars/_form.html.erb
<div class="form-group">
  <!--Error Message-->
  <% if car.errors.any? %>
    <div style="color: red">
      <h2>
          <%= pluralize(car.errors.count, "error" ) %> prohibited this car from being saved:
      </h2>
      <ul>
        <% car.errors.each do |error| %>
          <li>
            <%= error.full_message %>
          </li>
          <% end %>
      </ul>
    </div>
  <% end %>
  <!-- Form Started Here -->
  <%= form_with(model: car) do |form| %>
    <div>
      <%= form.label :company, class:"mt-3"%>
      <%= form.text_field :company, class:"mb-2 form-control" %>
    </div>
    <div>
      <%= form.label :model, style: "display: block" %>
      <%= form.text_field :model, class:"mb-2 form-control" %>
    </div>
    <div>
      <%= form.label :purchase_date, style: "display: block" %>
      <%= form.date_select :purchase_date, start_year: 1800, end_year: Time.now.year, class:"mb-2 fa fa-calendar"
          %>
    </div>
    <div class="dropdown-style">
      <%= form.label :engine_type, style: "display: block" %>
      <%= form.select(:engine_type, Car.engine_types.keys.map {|key| [key.humanize, key]}) %>
    </div>
    <div class="dropdown-style">
      <%= form.label :car_type, style: "display: block" %>
      <%= form.select(:car_type, Car.car_types.keys.map {|key| [key.humanize, key]}) %>
    </div>
    <div>
      <%= form.label :seats, style: "display: block" %>
      <%= form.number_field :seats, class:"mb-2 form-control" %>
    </div>
    <div>
      <%= form.label :distance_driven, style: "display: block" %>
      <%= form.number_field :distance_driven, class:"mb-2 form-control" %>
    </div>
    <div class="dropdown-style">
      <%= form.label :transmission_type, style: "display: block" %>
      <%= form.select(:transmission_type, Car.transmission_types.keys.map {|key| [key.humanize, key]}) %>
    </div>
    <div>
      <%= form.label :car_description, style: "display: block" %>
      <%= form.text_area :car_description, class:"mb-2 form-control" %>
    </div>
    <div>
      <%= form.label :registered_number, style: "display: block" %>
      <%= form.text_field :registered_number, class:"mb-2 form-control" %>
    </div>
    <div>
      <%= form.hidden_field :owner_id, value: current_user.id %>
    </div>
    <div class="field">
      <%= form.label :main_car_image %>
      <%= form.file_field :main_car_image %>
    </div>
    <div class="field">
      <%= form.label :car_images, "Upload Car Images:" %>
      <%= form.file_field :car_images, multiple: true %>

    <div>
      <%= form.label :For_Sell %>
      <%= form.check_box :sell, id: "sell", onchange: "sell_check()", checked: car.purpose.include?("sell") ? true : false  %>
    </div>

    <div>
      <%= form.label :For_rent %>
      <%= form.check_box :rent, id:"rent", onchange: "rent_check()", checked: car.purpose.include?("rent") ? true : false %>
    </div>

    <% sell_display_style = car.purpose.include?("sell") ? 'block' : 'none' %>
    <div style="display:<%= sell_display_style %>" id= "sell_div" >
      <%= form.label :Sell_Price, style: "display: block" %>
      <%= form.number_field :sell_price, class:"mb-2 form-control", id: "sell_price" %>
    </div>

    <% rent_display_style = car.purpose.include?("rent") ? 'block' : 'none' %>
    <div style="display:<%= rent_display_style %>" id= "rent_div" >
      <%= form.label :Rent_Price, style: "display: block" %>
      <%= form.number_field :rent_price, class:"mb-2 form-control", id: "rent_price" %>
    </div>

    <div>
      <%= form.submit class:"btn-secondary border-0 shadow py-2 px-5" %>
    </div>

  <% end %>
</div>

<script type="text/javascript">

    function sell_check() {

        if (document.getElementById('sell').checked == true) {
            document.getElementById('sell_div').style.display = "block";
        } else {
          document.getElementById('sell_div').style.display = "none";
        }
    }

    function rent_check() {

        if (document.getElementById('rent').checked == true) {
            document.getElementById('rent_div').style.display = "block";
        } else {
          document.getElementById('rent_div').style.display = "none";
        }
    }

</script>

app/views/cars/become_dealer.html.erb
<div class="container">
  <div class="card" style="width: 50rem;">
  <% if @user.errors.any? %>
    <div style="color: red">
      <h2>
          <%= pluralize(@user.errors.count, "error" ) %> prohibited this car from being saved:
      </h2>
      <ul>
        <% @user.errors.each do |error| %>
          <li>
            <%= error.full_message %>
          </li>
          <% end %>
      </ul>
    </div>
  <% end %>
    <div class="card-body ">
      <h4 class="card-title text-center">Become A Dealer</h4>
        <%= form_with model: @user, url: set_dealer_path do |form| %><br>
          <div class='dropdown-style'>
          <%= form.select(:payment_gateway, User.payment_gateways.keys.map {|key| [key.humanize, key]}) %><br><br>
          <%= form.label :Secret_key %><br/>
          <%= form.password_field :Secret_key,class: "mb-2 form-control" %>
          <%= form.label :Public_key %><br/>
          <%= form.password_field :Public_key,class: "mb-2 form-control" %>
          <%= form.submit class:"btn btn-primary"%><br>
        <%end%>
    </div>
  </div>  
</div>  

app/views/cars/edit.html.erb
<div>
  <div class="card mx-auto"  style="width: 30rem;">
    <div class="card-header">
      <h2 class="text-center">Edit Car's Details</h2>
    </div>
    <div class="card-body">
      <%= render "form" , car: @car %>
      <br/>
        <div>
          <%= link_to "Back to cars" , cars_path , class:"btn-secondary border-0 shadow py-2 px-5"%>
        </div>
    </div>
  </div>

  <div>
  <% if @car.main_car_image.key?%>
    <p> 
      <strong>Main Car Image:</strong>
    </p>
    <p>
      <%= cl_image_tag(@car.main_car_image.key, height: 200, width: 200) %>
    </p>
  <% end %>
  <% if @car.has_car_images?%>
    <p>
    <strong>Car Images:</strong>
    <% @car.car_images.each do |image| %>
      <div style="display: inline-block; width: 200">
        <%#= link_to(cl_image_tag(image.key, height: 200, width: 200, gravity: :auto, crop: :thumb, sign_url: true, fetch_format: :auto), url_for(image)) %>
        <%= cl_image_tag(image.key, height: 200, width: 200) %>
        <p style="text-align: center;">
          <%= button_to 'Delete Image', delete_car_image_car_path(@car),params: {image_id:image.id}, method: :delete, data: { confirm: 'Are you sure?' } %>
        </p>
      </div>
    <% end %>
  <% end %>
</div>

app/views/cars/index.html.erb
<section>
  <div class="container">
    <div class="row d-flex justify-content-evently">
      <% @cars.each do |car| %>
        <%= render car %>
      <%end%>
    </div>
  </div>
</section>

app/views/cars/new.html.erb
<div>
  <div class="card mx-auto" style="width: 30rem;">
    <div class="card-header">
      <h2 class="text-center">Register Car</h2>
    </div>
    <div class="card-body">
      <%= render "form" , car: @car %>
      <br/>
        <div>
          <%= link_to "Back to cars" , cars_path , class:"btn-secondary border-0 shadow py-2 px-5"%>
        </div>
    </div>
  </div>
</div>

app/views/cars/paypal_car_payment.html.erb
<div id="paypal-button-container"></div>
<p><%=@response %></p>
<script src="https://www.paypal.com/sdk/js?client-id=AfLOwpfasi3e8fgpbsH2piZILP5t4-cV_1baCz6-g7Si97exDwPxVLofLQsNnAbVMeEpZmEqLmwLvwgS"></script>
<script>
  paypal.Buttons({
  env: 'sandbox', // Valid values are sandbox and live.
  createOrder: async () => {
  const response = await fetch(`/create_paypal_car`, {method: 'POST'});
  const responseData = await response.json();
  console.log("--------createOrder-----------")
  return responseData.token;
  },
  onApprove: async (data) => {
  const response = await fetch('/capture_paypal_car', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json'
    },
    body: JSON.stringify({order_id: data.orderID})
  });
  const responseData = await response.json();
  if (responseData.status === 'COMPLETED') {
    alert('COMPLETED');
    console.log(responseData)
    // REDIRECT TO SUCCESS PAGE
  }
  }
  }).render('#paypal-button-container');
</script>

app/views/cars/show.html.erb
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" integrity="sha512-+4zCK9k+qNFUR5X+cKL9EIR+ZOhtIloNl9GIKS57V1MyNsYpYcUrUeQc9vNfzsWfV28IaLL3i96P9sdNyeRssA==" crossorigin="anonymous" />
  </head>
  <body>
    <div class = "card-wrapper">
      <div class = "card-car">
        <!--carousel-->
        <div id="carouselExampleIndicators" class="carousel slide product-imgs" data-bs-ride="carousel" style="width: 30rem;">
          <div class="carousel-indicators img-display">
            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
            <% i=1; j=2;%>
            <% @car.car_images.each do |car|%>
              <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="<%=i%>" aria-label="Slide <%=j%>"></button>
              <% i = i+1; j=j+1;%>
            <% end %>
          </div>
          <div class="carousel-inner">
            <div class="carousel-item active">
              <%= cl_image_tag(@car.main_car_image.key) %>
            </div>
            <% @car.car_images.each do |car|%>
              <div class="carousel-item">
                <%= cl_image_tag(car.key, class:"d-block w-100") %>
              </div>
            <% end %>
          </div>
          <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
          </button>
          <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
          </button>
        </div>
        <div class = "product-content" style="width: 50rem;">
          <h2 class = "product-title"><%= @car.company%><%= @car.model%></h2>
          <a class = "product-link"> Seller: <%= @car.owner.email%></a>
          <div class = "product-price">
            <% if @car.owner != current_user %>
              <% if @car.sell_price %>
                <div class="d-flex align-items-center justify-content-between">
                  <p class = "new-price">Sell Price: <span><%=@car.sell_price%></span></p>
                  <%= button_to "Buy",checkout_sell_path(@car), class:"btn btn-primary btn-sm", data: { turbo: false }, remote: true %>
                </div>
              <% end %>
              <% if @car.rent_price %>
                <div class="d-flex align-items-center justify-content-between mt-3">
                  <p class = "last-price">Rent Price: <span><%= @car.rent_price%></span></p>
                  <%= button_to "Rent",checkout_rent_path(@car), class:"btn btn-success btn-sm", data: { turbo: false }, remote: true %>
                </div>
              <% end %>
            <% else %>
              <% if @car.sell_price %>
                <div class="d-flex align-items-center justify-content-between">
                  <p class = "new-price">Sell Price: <span><%=@car.sell_price%></span></p>
                </div>
              <% end %>
              <% if @car.rent_price %>
                <div class="d-flex align-items-center justify-content-between mt-1">
                  <p class = "last-price">Rent Price: <span><%= @car.rent_price%></span></p>
                </div>
              <% end %>
            <% end %>
          </div>
          <div class = "product-detail">
            <h2>Description </h2>
            <p><%= @car.car_description %></p>
            <ul>
              <li>Model: <span><%= @car.purchase_date.year%></span></li>
              <li>Car Type: <span><%= @car.car_type%></span></li>
              <li>Transmission Type: <span><%= @car.transmission_type%></span></li>
              <li>Engine: <span><%= @car.engine_type%></span></li>
              <li>Capacity: <span><%= @car.seats%> seater</span></li>
              <li>DIstance Driven: <span><%= @car.distance_driven%> KMs</span></li>
            </ul>
          </div>
          <div class = "social-links">
            <p>Share At: </p>
            <a href = "#">
              <i class = "fab fa-facebook-f"></i>
            </a>
            <a href = "#">
              <i class = "fab fa-twitter"></i>
            </a>
            <a href = "#">
              <i class = "fab fa-instagram"></i>
            </a>
            <a href = "#">
              <i class = "fab fa-whatsapp"></i>
            </a>
            <a href = "#">
              <i class = "fab fa-pinterest"></i>
            </a>
          </div>
          <div>
            <br>
            <div>
              <% if can? :update, @car%>
                <%= link_to "Edit this car", edit_car_path(@car),class:"btn btn-outline-dark btn-sm me-2" %>
              <% end %>
              <%= link_to "Back to cars", cars_path,class:"btn btn-outline-primary btn-sm me-2" %>
              <% if can? :destroy, @car%>
                <%= link_to "Destroy this car", @car, method: :delete,class:"btn btn-outline-danger btn-sm" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>