config/routes.rb
Rails.application.routes.draw do
  root "cars#index"
  devise_for :users
  post 'checkout/sell/:id', to: "checkout#sell", as: :checkout_sell
  post 'checkout/rent/:id', to: "checkout#rent", as: :checkout_rent
  patch 'set_dealer', to: "cars#set_dealer", as: :set_dealer
  get 'search_for_cars', to: 'cars#search_for_cars'
  resources :cars do
    delete 'delete_car_image', on: :member
  end

  # for transction 
  resources :car_transactions do
    get 'car_sell_payment', on: :member
    post 'sell_payment', on: :collection
    post 'paypal_payment_response', on: :collection
  end
end

app/views/layouts/_errors.html.erb
<div>
  <% if flash[:alert] %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert" style="margin-top: -14px !important;">
      <%= flash[:alert] %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% elsif flash[:notice] %>
    <div class="alert alert-success alert-dismissible fade show" role="alert" style="margin-top: -14px !important;">
      <%= flash[:notice] %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
</div>

app/views/layouts/_navbar.html.erb
<!---navbar -->
<nav class="navbar navbar-expand-lg navbar fixed-top navbar-dark bg-dark ">
  <div class="container-fluid ">
    <a class="navbar-brand" href="#">
      <a href="/" class="me-2"><%= image_tag("Logo.svg",:size => "30x50")%></a>
      
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse parent" id="navbarSupportedContent">
      <ul class="navbar-nav mb-2 ms-5 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">About Us</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Services
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Buy</a></li>
            <li><a class="dropdown-item" href="#">Rent</a></li>
          </ul>
        </li>
      </ul>
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0"">
          <li class="nav-item">
            <% if params[:action]=='index'%>
            <%= form_tag cars_path, :method => 'get',class:"d-flex" ,local:true do %>
              <%= text_field_tag :query, params[:query], id:"query", class:"form-control me-2", placeholder: 'Search' %>
              <%= submit_tag "Search", class:"btn btn-outline-success me-5"%>
            <% end %>
          <% end %>
          </li>
        </ul>
      <% if signed_in? %>
        <li class="nav-item dropdown">
          <a class="btn btn-outline-light me-2 dropdown-toggle" href="#" id="navbarDropdown1" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <%= current_user.email%>
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown1">
            <li><%= link_to "Profile", edit_user_registration_path,class:"dropdown-item" %></li>
          
            <li><%= link_to "Become a Dealer", new_car_path , class:"dropdown-item"%></li>
            <li><%= link_to "My Cars",root_path(my_cars: "my_cars"), class:"dropdown-item" %>
            </ul>
          </li>
          <%= button_to "Log out", destroy_user_session_path, method: :delete, data: { turbo: "false" }, class:"btn btn-outline-danger" %>
        <% else %>
          <ul class="navbar-nav mb-2 mb-lg-0">
            <li class="nav-item">
              <%= link_to "Log in", new_user_session_path, class:"btn btn-outline-warning me-2" %>
              <%= link_to "Register", new_user_registration_path, class:"btn btn-outline-primary" %>
            </li>
          </ul>
        <% end %>
    </div>
</nav>

<!--To add elasticsearch autocomplete -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<%= render 'layouts/typeahead_bundle_Js'%>
<script>
  var cars = new Bloodhound({
    datumTokenizer: Bloodhound.tokenizers.whitespace,
    queryTokenizer: Bloodhound.tokenizers.whitespace,
    remote: {
      url: '/search_for_cars?query=%QUERY',
      wildcard: '%QUERY'
    }
  });
  $('#query').typeahead(null, {
    highlight: true,
    source: cars
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GoCars</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://js.stripe.com/v3/"></script>
    <%= favicon_link_tag 'Favicon.svg' %>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    
    <!-- Boostrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </head>
  <body>
    <div>
      <%= render 'layouts/navbar' %>
    </div>
      <%= render 'layouts/errors' %>
    <%= yield %>
  </body>
</html>